### ISSUE TITLE
Secure Loki

### ISSUE THREAD

**Issue by k1g99** [skkuding/codedang-monitor#5]
### Describe the problem and solution

~~보안을 위해서 promtail과 loki 사이에 TLS 적용하기~~
학교 방화벽 설정으로 로컬(2번 서버)에서 로컬(3번 서버)로 보내는 것은 굳이 보안 설정을 하지 않아도 됨.
따라서 외부 production 환경 (AWS)에서 On-premise로 보내는 보안환경을 구축

참고
- https://community.grafana.com/t/secure-loki-and-promtail-via-tls/59808
- https://github.com/mikequentel/caddy-and-loki-deployment-example

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by goathoon** [comment]
https://grafana.com/docs/loki/latest/operations/authentication/
앞에 Caddy놓고 uname pwd 설정 가능한지 확인

**Comment by goathoon** [comment]
Caddy 넣고 uname - pwd를 한다는거 자체가 멍청한 생각이었음.

당초에 promtail 과 loki는 리버스 프록시의 대상이 되는 요청이 아니기 때문에 (ip:포트로 직접 전송), 저 방법은 의미 없고, TLS를 적용하는 방법이 올바르다고 생각

**Comment by k1g99** [comment]
> Caddy 넣고 uname - pwd를 한다는거 자체가 멍청한 생각이었음.
> 
> 당초에 promtail 과 loki는 리버스 프록시의 대상이 되는 요청이 아니기 때문에 (ip:포트로 직접 전송), 저 방법은 의미 없고, TLS를 적용하는 방법이 올바르다고 생각

그럼 AWS 랑 Loki랑 통신할 때는 적용이 가능한가요??
